main:
  port: 8080
  read_timeout: 10s
  write_timeout: 10s
  read_header_timeout: 10s
  idle_timeout: 30s
  shutdown_timeout: 10s
session:
  refresh_token_length: 128
  access_token_length: 64
  access_token_life_time: 86400s
  access_token_cookie_name: pet_adopter_session
  protected_cookies: false
validation:
  username_min_length: 3
  username_max_length: 20
  password_min_length: 8
  password_max_length: 64
ad:
  max_price: 1000000
  default_search_limit: 20
  default_search_offset: 0
  max_search_limit: 1000
  photo:
    max_form_data_size: 31457280 # 30 * 1024 * 1024 (30 МБ)
    file_types:
      image/jpeg: .jpeg
      image/webp: .webp
      image/png: .png
    request_field_name: photo
  create_form_field_name: form
chat_gpt:
  base_url: https://api.openai.com
  responses_url: /v1/responses
  model: gpt-4o-mini
color:
  max_part_distance: 30
  max_sum_distance: 60
